### ISSUE TITLE
Icould not join your voice channel: Error: Couldn't find an Opus engine

### ISSUE THREAD

**Issue by bycop** [Spimy/Music-Bot-Development#2]
My bot wouldn't play any music / Video and he say

ready.js:10
I could not join your voice channel: Error: Couldn't find an Opus engine.
functions.js:80

Thanks you

**Comment by Spimy** [comment]
Hello, sorry for late reply.
You will need to install node-opus or opusscript.
To do so, go to the bot's folder and shift right click to open a command prompt or powershell and type in "npm i opusscript"

**Comment by Kruku2006** [comment]
My bot not playing a music

error:
I could not join your voice channel: Error: FFMPEG not found
pls help me
thanks you
