### ISSUE TITLE
My bot not playing a music

### ISSUE THREAD

**Issue by Kruku2006** [Spimy/Music-Bot-Development#3]
My bot not playing a music

error:
I could not join your voice channel: Error: FFMPEG not found
Pls help me
Thanks you

**Comment by Spimy** [comment]
Hello, install FFMPEG on the machine you are running the bot on :)
Download it at: https://ffmpeg.org/
If you need any help installing, there are many tutorials on YouTube 😄

**Comment by Spimy** [comment]
> My bot not playing a music
> 
> error:
> I could not join your voice channel: Error: FFMPEG not found
> Pls help me
> Thanks you

Hello, install FFMPEG on the machine you are running the bot on :)
Download it at: https://ffmpeg.org/
If you need any help installing, there are many tutorials on YouTube 😄

**Comment by Kruku2006** [comment]
hi my bot is already working, but the unfinished sends a message to the channel that it plays music, and after a while sends that the music is over, I have no idea what is the reason for this action. will you help me? thanks

**Comment by Spimy** [comment]
> hi my bot is already working, but the unfinished sends a message to the channel that it plays music, and after a while sends that the music is over, I have no idea what is the reason for this action. will you help me? thanks

I don't understand what u mean. U mean the song ends the moment u play it? This seems to be an issue with ytdl-core. I personally don't have this issue, but if you still continue to experience this issue, use ytdl-core-discord. If you need further help Ømega#5556 on my Discord can help u

**Comment by nestormaldonado** [comment]
Hi

i have the same error. When I put a song the bot joins and leaves immediately...

I've tried to change everything and I still can't get it... And I think I have everything right.
I sent you a request in discord


**My discord: Modz#0001**

**Comment by Spimy** [comment]
> Hi
> 
> i have the same error. When I put a song the bot joins and leaves immediately...
> 
> I've tried to change everything and I still can't get it... And I think I have everything right.
> I sent you a request in discord
> 
> **My discord: Modz#0001**

Hello, I cannot seem to see you on Discord. My tag at this moment is Misaki#6160
Also, this music bot is really outdated and no longer works. If you need any sort of help, join my discord server @ http://discord.spimy.ga for help from other developers. This issue is because of YTDL-Core and you should switch over to YTDL-Core-Discord which I have no experience using.
